name: Update YouTube Views

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * 1'

jobs:
  update-views:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Update YouTube views
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          UPDATE_SECRET: ${{ secrets.UPDATE_SECRET }}
        run: |
          python update_views.py
